server:
  port: 9002
  servlet:
    context-path: /pay


spring:
  thymeleaf:
    cache: false
  application:
    name: micr-pay

dubbo:
  registry:
    address: zookeeper://localhost:2181
  scan:
    base-packages: com.bjpowernode
  consumer:
    timeout: 8000
    check: false