spring:
  application:
    name: micr-task

dubbo:
  registry:
    address: zookeeper://localhost:2181
  scan:
    base-packages: com.bjpowernode.task
  consumer:
    check: false
    retries: 0
    timeout: 8000


pay:
  kqUrl: http://localhost:9002/pay/kq/query