server:
  port: 8000
  servlet:
    context-path: /licai

spring:
  application:
    name: micr-web
  thymeleaf:
    cache: false
  redis:
    host: localhost
    port: 6379


dubbo:
  registry:
    address: zookeeper://localhost:2181
  scan:
    base-packages: com.bjpowernode.web
  consumer:
    timeout: 100000
    retries: 0
    check: false

#写短信发送的配置类
jdwx:
  sms:
    url: https://way.jd.com/chuangxin/dxjk
    content: 【动力金融】你的验证码是：%s，3分钟内有效！
    appkey: 3680fa919b771148da626bbcbd459475
  realname:
    url: https://way.jd.com/youhuoBeijing/test
    appkey: 3680fa919b771148da626bbcbd459475


#micr-pay 访问地址
pay:
  kqurl: http://localhost:9002/pay/kq
  baofuurl: http://localhost:9002/pay/baofu